### ISSUE TITLE
Failing finaly.js test - Promise rejected with no or falsy reason

### ISSUE THREAD

**Issue by vnovick** [benjamingr/bluebird-api#65]
#goodnessSquad

```
1) finally runs on rejection:
     Error: Promise rejected with no or falsy reason
      at runMicrotasksCallback (internal/process/next_tick.js:64:5)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

reject has to be an instance of Error

**Comment by MadaraUchiha** [comment]
Fixed by #64
